# Use the official Node.js image
FROM node:current-bullseye

# Set working directory to /workspaces/js_experimental
# WORKDIR /workspaces/js_experimental

# Install TypeScript globally
RUN npm install -g typescript

# Expose the port for Storybook
EXPOSE 6006
